### ISSUE TITLE
Slow sort on gfx1036 with custom operator on ROCm 5.6.0

### ISSUE THREAD

**Issue by Oblomov** [ROCm/rocThrust#310]
I have an AMD Ryzen 9 7900X 12-core / 24-threads processor and I'm trying to run our code on both the CPU and iGP `0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c2)` for comparison. 

Some of our code depends on Thrust, for which we are using rocThrust for HIP (1.17.2p0 as reported by the one shipping with ROCm 5.6.0, official .deb from AMD).

We have noticed that a sort_by_key with custom operator is extremely slow on GPU, averaging 30ms for 1.4M data points compared to  ~20ms on CPU with the OpenMP backend.

Sample code for testing can be found in my [titanxstall](https://github.com/Oblomov/titanxstall) repo, `rocthrust-perf` branch. The results can be tested as:
```
git clone git@github.com:Oblomov/titanxstall -b rocthrust-perf thrust-perf
cd thrust-perf
make clean ; make test
make clean ; make cpu=1 openmp=1 test
```
and comparing the results between the HIP and OpenMP runs. The sort is run 5 times, and on GPU the first run should be discarded as it includes host-to-device data transfers due to the use of managed allocations. (The original code does *not* use managed allocations, but similar performance differences have been observed, so this doesn't seem to be related.)

**Comment by ppanchad-amd** [comment]
@Oblomov Apologies for the lack of response. gfx1036 isn't an architecture we officially support, so we unfortunately cannot provide support.  Please see the supported GPU's (https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html). Thanks!
