### ISSUE TITLE
How to include a custom header library version?

### ISSUE THREAD

**Issue by klausbu** [ROCm/rocThrust#407]
hipcc --offload-arch=gfx1031 -I/opt/rocm-5.4.0/myspecialrocm/include/thrust -I/opt/rocm-5.4.0/myspecialrocm/include/rocprim discrete_voronoi.cu -o testvoronoi

I tried to redirect hipcc to my custom version of rocThrust but it mixes (see >> comments) the custom and the default installations when I try to compile a program. 

hipcc --offload-arch=gfx1031 -I/opt/rocm-5.4.0/myspecialrocm/include/thrust -I/opt/rocm-5.4.0/myspecialrocm/include/rocprim discrete_voronoi.cu -o testvoronoi

In file included from <built-in>:1:
In file included from /opt/rocm-5.4.0/llvm/lib/clang/15.0.0/include/__clang_hip_runtime_wrapper.h:115:
In file included from /opt/rocm-5.4.0/llvm/lib/clang/15.0.0/include/__clang_hip_math.h:22:
In file included from /opt/rocm-5.4.0/myspecialrocm/include/thrust/limits.h:10:   >> using custom version, ok
In file included from /opt/rocm-5.4.0/include/thrust/detail/config.h:23:   >> using default version, not ok
In file included from /opt/rocm-5.4.0/include/thrust/detail/config/config.h:26:   >> using default version, not ok
In file included from /opt/rocm-5.4.0/include/thrust/detail/config/compiler.h:29:   >> using default version, not ok
In file included from /opt/rocm-5.4.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-5.4.0/include/hip/amd_detail/amd_hip_runtime.h:105:
/opt/rocm-5.4.0/include/hip/hip_runtime_api.h:5243:25: error: use of undeclared identifier 'UINT_MAX'
    size_t size __dparm(UINT_MAX));
                        ^
/opt/rocm-5.4.0/include/hip/hip_runtime_api.h:6790:75: error: use of undeclared identifier 'UINT_MAX'
                                        const void* devPtr, size_t size = UINT_MAX) {
                                                                          ^
/opt/rocm-5.4.0/include/hip/hip_runtime_api.h:6797:75: error: use of undeclared identifier 'UINT_MAX'
                   const struct hipChannelFormatDesc& desc, size_t size = UINT_MAX) {
                                                                          ^

The example is an example included in rocThrust and was compiled correctly when I installed rocThrust and opted to compile the examples, now I want to make use of the custom version to port software to work on my notebook but am not able to compile a program. I assume the resulting errors are caused by the parts pulled from the default rocThrust rocm stack that doesn't support my GPU.

What's the correct way to enforce the use of the custom version?

**Comment by lamb-j** [comment]
@stanleytsang-amd Can you take a look at and comment on the last two points from @klausbu above?

We can transfer the issue over to llvm-project with the 'hipcc' tag if we still think the fix should come from there, but I wanted to get your opinion on it as well. Thanks!

**Comment by Naraenda** [comment]
> What's the minimum development environment needed to be able to achieve my objective?

The simplest would be to build and install the modified rocPRIM in a docker image (i.e. rocm-terminal), and then build and install rocThrust. You can reference `.gitlab-ci.yml`: https://github.com/ROCm/rocThrust/blob/e0a9a0294cd6605ac557227040b87e68cc6b8170/.gitlab-ci.yml#L56-L74

**Comment by ppanchad-amd** [comment]
@klausbu Do you still need assistance with this issue? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@klausbu. Closing ticket due to lack of activity. Please feel free to re-open ticket if you still need assistance. Thanks!
